create table if not exists  app.app_user_predict_first_invest_predict_set_from_1
(
user_id                 string,
age_generation          string,
gender_code             string,
telecom_operators       string,
is_member               string,
lv_name                 string,
has_bind_bank_card      string,
card_value              string,
mobile_value            string,
mobile_phone_value      string,
is_register_ump_good    string,
is_new_user_loan        string,
is_register_recharge_good  string,
is_register_invest_good string,
is_ump_recharge_good    string,
is_ump_invest_good      string,
is_recharge_invest_good string,
zodiac                  string,
chinese_zodiac          string,
mobile_province         string,
first_invest_date       string,
first_invest_amount     string,
first_invest_loan_months string,
first_invest_rate       string,
first_recharge_date     string,
first_recharge_amount   string,
dt                      string
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';